baseURL = "https://huizhixu.github.io/"
languageCode = "zh-cn"
title = "HuizhiXu 的个人博客"
theme = "github-style"


[params]
  author = "Huizhi"
  email = "xuhuizhi@hotmail.com"
#   url = "https://huizhixu.org"
  lastmod = true
  userStatusEmoji = "😀"
  favicon = "/images/poirot.png"
  location = "China"
  enableGitalk = true

  [params.gitalk]
    clientID = "Your client ID"
    clientSecret = "Your client secret"
    repo = "repo"
    owner = "Huizhi"
    admin = "Huizhi"
    id = "location.pathname"
    labels = "gitalk"
    perPage = 15
    pagerDirection = "last"
    createIssueManually = true
    distractionFreeMode = false


[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

 publishDir = "docs"