name: Notion To Blog

on:
  issues:
    types: [opened]

jobs:
  notion-to-blog:
    if: ${{ github.event.issue.user.login == github.actor && contains(github.event.issue.title, 'notion-ci') }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Blog Repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.CHECKOUT_TOKEN }}
        fetch-depth: 0

    - name: Checkout Pictures Repository
      uses: actions/checkout@v2
      with:
        repository: HuizhiXu/pictures
        token: ${{ secrets.CHECKOUT_TOKEN }}
        path: pictures_repo

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.135.0'
        extended: true

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: python -m pip install notion-client md2notion python-frontmatter pyyaml requests

    - name: Run Notion to Blog Script
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        CHECKOUT_TOKEN: ${{ secrets.CHECKOUT_TOKEN }}
        POST_DIR: 'content/chs/know_how'
        GITHUB_REPO: 'HuizhiXu/pictures'
      run: python scripts/notion_to_blog.py

    - name: Commit and Push Pictures
      working-directory: pictures_repo
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -m "Add new images from Notion"
        git push

    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'

    - name: Initialize and Update Submodules
      run: |
        git submodule init
        git submodule update --recursive

    - name: Run Deploy Script
      run: |
        chmod +x deploy.sh
        ./deploy.sh "Auto deploy from GitHub Actions"
