name: Notion To Blog

on:
  issues:
    types: [opened]

jobs:
  notion-to-blog:
    if: ${{ github.event.issue.user.login == github.actor && contains(github.event.issue.title, 'notion-ci') }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Blog Repository
      uses: actions/checkout@v4
      with:
        repository: HuizhiXu/huizhixu.org
        token: ${{ secrets.CHECKOUT_TOKEN }}
        fetch-depth: 0
        submodules: false

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.135.0'
        extended: true

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: python -m pip install notion-client md2notion python-frontmatter pyyaml requests

    - name: Copy Scripts
      run: |
        mkdir -p scripts
        curl -o scripts/notion_to_blog.py https://raw.githubusercontent.com/HuizhiXu/huizhixu.org/master/scripts/notion_to_blog.py

    - name: Run Notion to Blog Script
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        CHECKOUT_TOKEN: ${{ secrets.CHECKOUT_TOKEN }}
        POST_DIR: 'content/chs/know_how'
        GITHUB_REPO: 'HuizhiXu/pictures'
        GITHUB_BRANCH: 'master'
      run: python scripts/notion_to_blog.py

    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'

    - name: Commit Changes
      run: |
        git add content/
        git commit -m "Add new blog posts from Notion" || echo "No changes to commit"
        git push origin master || echo "No changes to push"

    - name: Build Hugo site
      run: hugo --buildDrafts=false -t blist

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.CHECKOUT_TOKEN }}
        publish_dir: ./public
        external_repository: HuizhiXu/huizhixu.github.io
        publish_branch: master
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'