name: Notion To Blog

on:
  issues:
    types: [opened]

jobs:
  notion-to-blog:
    if: ${{ github.event.issue.user.login == github.actor && contains(github.event.issue.title, 'notion-ci') }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.CHECKOUT_TOKEN }}

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.135.0'
        extended: true

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install notion-sdk-py md2notion python-frontmatter pyyaml requests

    - name: Run Notion to Blog Script
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        POST_DIR: 'content/chs/know_how'
      run: python scripts/notion_to_blog.py

    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'

    - name: Initialize and Update Submodules
      run: |
        git submodule init
        git submodule update --recursive

    - name: Run Deploy Script
      run: |
        chmod +x deploy.sh
        ./deploy.sh "Auto deploy from GitHub Actions"
